name: First pipeline
on:
  push: 
    branches: [ main ]
  workflow_dispatch: 

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Print hello linux
        run: echo "hello from Linux VM"

  job-2:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Print hello window
        run: echo "hello from Windows VM"
